### PR TITLE
Implement Like System

### PR DESCRIPTION
**Pull request by NasserBen**

### CODE REVIEW

**Review by jeralsonep — COMMENTED** [review]
Recieving an extensive error, starting with the following when liking a post:

` ⨯ RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 0`

**Comment by jeralsonep** [comment]
Also just created a new post (i.e. Cookies) and it only shows in the homepage, not under user _Chiefly's_ profile page. Also noticed the user setting dropdown is gone. Assuming it's a work in progress.

**Comment by NasserBen** [comment]
> etting drop

I was unable to replicate this error.

**Comment by NasserBen** [comment]
> Also just created a new post (i.e. Cookies) and it only shows in the homepage, not under user _Chiefly's_ profile page. Also noticed the user setting dropdown is gone. Assuming it's a work in progress.

Wym user setting dropdown? U mean the settings icon?

**Comment by jeralsonep** [comment]
yeah the settings icon is what I meant, mb

**Comment by NasserBen** [comment]
> yeah the settings icon is what I meant, mb. if you merge to main ill retest

If your not logged in to that user it wont display. It only displays when ur logged in.

**Pull request closed without merging**
